### ISSUE TITLE
Would this work with Environment variables outside .env?

### ISSUE THREAD

**Issue by ingalless** [JulienTant/Laravel-Env-Sync#24]
Hi! Great package!

We would like to use this as part of a CI/CD deployment pipeline but wonder whether it would work in that instance?
For example, Azure will set environment variables on the "machine" instead of creating a .env file. Would this support that scenario? A quick glance didn't make it seem as though it would

Happy to put the work in to make it do so if not 👍

**Comment by JulienTant** [comment]
Hi,

The point of the package is just to check that your `.env` file is in sync with the `.env.example` and does not provide any kind of validation regarding the fact that a variable exists. It just operate a file content comparison (kinda).

I feel like it's out of scope of this package right now, but i'm glad to read more about it if you disagree!

**Comment by ingalless** [comment]
Thanks for the quick reply!

Having the ability to ensure that the ENV variable is present as a check for a deployment pipeline would be fantastic for verifying safe deployments.

But I understand not wanting to increase the package beyond its scope. Perhaps I'll just have to steal it for my own open source package!
I wouldn't want to add to the complexity of the package unnecessarily for a feature which needn't be here.

If it seems like it _could_ benefit this package I'll swing back round and add a pull request here.
Thanks for this package though! Looking forward to including it in my development flow 👍
