### ISSUE TITLE
require php version 5.6+

### ISSUE THREAD

**Issue by Easter1021** [JulienTant/Laravel-Env-Sync#4]
> ---

> because 2 reasons, you need require 5.6+

> ---

### reason 1  `laravel-env-sync/src/SyncService.php line 38`

![2016-09-01 4 18 47](https://cloud.githubusercontent.com/assets/1082597/18161569/0d96155c-7065-11e6-840d-dacb719cefe2.png)
![2016-09-01 4 04 07](https://cloud.githubusercontent.com/assets/1082597/18161460/902817a0-7064-11e6-9741-fe733a9c5e1d.png)
![2016-09-01 4 29 55](https://cloud.githubusercontent.com/assets/1082597/18161495/c0097284-7064-11e6-950a-0bcb7c1c186a.png)

---

### reason 2  `laravel-env-sync/src/SyncService.php line 35`
![2016-09-01 4 58 40](https://cloud.githubusercontent.com/assets/1082597/18161643/5e37d568-7065-11e6-8ad7-45a071cc9132.png)
![2016-09-01 4 18 30](https://cloud.githubusercontent.com/assets/1082597/18161486/ae23865e-7064-11e6-9c02-832adc2c2df1.png)
![2016-09-01 4 25 25](https://cloud.githubusercontent.com/assets/1082597/18161671/821cd690-7065-11e6-8a74-038c807112e7.png)

**Comment by JulienTant** [comment]
Fixed by https://github.com/JulienTant/Laravel-Env-Sync/commit/4e27725546c4e970a74b30d33fb9d98c0f99a0e0

Thanks for reporting !
