### ISSUE TITLE
Not working if add it to the composer post-install-cmd

### ISSUE THREAD

**Issue by max-kovpak** [JulienTant/Laravel-Env-Sync#8]
I added "php artisan env:sync" to the post-install-cmd in my composer.json and it not working. It asks to set some variable then shows [ERROR] Aborted then asks again and again [ERROR] Aborted.

` [ERROR] Aborted

 'SOME_TEST' is not present into your .env file. Its default value is 'test'. Would you like to add it ? [y=yes/n=no/c=change default value] [Copy the default value]:
  [y] Copy the default value
  [c] Change the default value
  [n] Skip
 >

 [ERROR] Aborted

 'SOME_TEST' is not present into your .env file. Its default value is 'test'. Would you like to add it ? [y=yes/n=no/c=change default value] [Copy the default value]:
  [y] Copy the default value
  [c] Change the default value
  [n] Skip
 >

 [ERROR] Aborted

 'SOME_TEST' is not present into your .env file. Its default value is 'test'. Would you like to add it ? [y=yes/n=no/c=change default value] [Copy the default value]:
  [y] Copy the default value
  [c] Change the default value
  [n] Skip
 >

 [ERROR] Aborted

 'SOME_TEST' is not present into your .env file. Its default value is 'test'. Would you like to add it ? [y=yes/n=no/c=change default value] [Copy the default value]:
  [y] Copy the default value
  [c] Change the default value
  [n] Skip
 >

 [ERROR] Aborted

 'SOME_TEST' is not present into your .env file. Its default value is 'test'. Would you like to add it ? [y=yes/n=no/c=change default value] [Copy the default value]:
  [y] Copy the default value
  [c] Change the default value
  [n] Skip
 >

 [ERROR] Aborted`

**Comment by JulienTant** [comment]
I just did a test and can't reproduce the problem. 

I just added 

```json 
"post-install-cmd": [
    "php artisan env:sync"
]
```

to my composer.json file and it worked like a charm.
